table financials
	lineageTag: 194baf60-d0f5-4144-a2b9-35b8ff3255e9

	column Segment
		dataType: string
		lineageTag: e27010dd-dd92-44eb-8fbb-074362d78836
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: e0c458d7-3562-4781-b8f9-7134395cd2cd
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: d0b9fd1a-720f-4a5d-a965-ed7dd5185b1c
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: ae494159-0555-47a8-b895-e32ac90593eb
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: int64
		formatString: 0
		lineageTag: 8028390c-85bd-412d-aa9b-ece49df43490
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: 11374d06-ad22-47cf-86f7-afe06783b74e
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: 8ea3d320-90e0-4240-bbf2-df748abe3850
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: 9bdff7a5-0e1c-46c3-a064-2a9842772fe2
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: 5823eff9-230c-4d6d-b851-19f705f19d16
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 9c784007-9077-4d5e-8457-040b2600414a
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: 21169e5f-56bb-46ed-8bb7-93a20c39855f
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 935a550c-740a-412a-8c67-6afe8bbcdb5a
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ec6c5168-2f8c-4fbd-9833-e75b085f635b
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: fd93d189-4280-4fcf-8aae-de5608041ac1
			defaultHierarchy: LocalDateTable_c1d205aa-f9d7-4cfc-9488-3a9a4bdd8768.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 2a44b50c-29ed-4d0f-9bf9-bd7e9f550ef6
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 163d30da-786c-4df2-93a1-54b1b7ceff19
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: a750b18b-3b40-4ad0-9ca8-06e85f532547
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition financials = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.157.879.0_x64__8wekyb3d8bbwe\bin\SampleData\Financial Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}}),
				    #"Arredondado para Baixo" = Table.TransformColumns(#"Tipo Alterado",{{"Units Sold", Number.RoundDown, Int64.Type}}),
				    #"Texto em Maiúscula" = Table.TransformColumns(#"Arredondado para Baixo",{{"Month Name", Text.Upper, type text}}),
				    #"Linhas Classificadas" = Table.Sort(#"Texto em Maiúscula",{{"Year", Order.Descending}})
				in
				 #"Linhas Classificadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

